# Generated by Django 4.0.1 on 2022-01-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_guest_name_alter_guest_user'),
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='downvoted_users',
            field=models.ManyToManyField(blank=True, related_name='downvoted_comment_users', to='user.Guest'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='comment_saved_by', to='user.Guest', verbose_name='comment saved by'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvoted_users',
            field=models.ManyToManyField(blank=True, related_name='upvoted_comment_users', to='user.Guest'),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvoted_users',
            field=models.ManyToManyField(blank=True, related_name='downvoted_post_users', to='user.Guest'),
        ),
        migrations.AlterField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='post_saved_by', to='user.Guest', verbose_name='post saved by'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvoted_users',
            field=models.ManyToManyField(blank=True, related_name='upvoted_post_users', to='user.Guest'),
        ),
    ]
