# Generated by Django 3.2.5 on 2021-08-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='child_comments',
            field=models.ManyToManyField(to='BlogApp.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.post'),
        ),
    ]
