# Generated by Django 4.0.1 on 2022-01-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_comment_text_alter_post_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='child_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.comment'),
        ),
    ]
