# Generated by Django 4.0.1 on 2022-01-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_comment_downvoted_users_alter_comment_saved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='number_of_comments',
        ),
    ]
