# Generated by Django 4.0.1 on 2022-01-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_remove_comment_child_comments_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(null=True, to='BlogApp.Comment'),
        ),
    ]
