# Generated by Django 4.0.4 on 2022-05-15 16:08

from django.db import migrations, models


def add_owner(apps, schema_editor):
    MyModel = apps.get_model('BlogApp', 'Comment')
    for row in MyModel.objects.all():
        row.owner_id = row.user.id
        row.save(update_fields=['owner_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_alter_comment_downvoted_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='owner id'),
        ),
        migrations.RunPython(add_owner, reverse_code=migrations.RunPython.noop),
    ]
