# Generated by Django 4.0.1 on 2022-01-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220107_0901'),
        ('BlogApp', '0006_comment_rating_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvoted_users',
            field=models.ManyToManyField(related_name='downvoted_comment_users', to='user.Guest'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoted_users',
            field=models.ManyToManyField(related_name='upvoted_comment_users', to='user.Guest'),
        ),
        migrations.AddField(
            model_name='post',
            name='downvoted_users',
            field=models.ManyToManyField(related_name='downvoted_post_users', to='user.Guest'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvoted_users',
            field=models.ManyToManyField(related_name='upvoted_post_users', to='user.Guest'),
        ),
    ]
