# Generated by Django 4.0.4 on 2022-05-16 09:00

from django.db import migrations, models


def add_owner(apps, schema_editor):
    MyModel = apps.get_model('BlogApp', 'Comment')
    for row in MyModel.objects.all():
        row.owner_pfp_url = row.user.profile_picture.url
        row.save(update_fields=['owner_pfp_url'])


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_add_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='owner_pfp_url',
            field=models.CharField(blank=True, max_length=256, verbose_name='owner pfp url'),
        ),
        migrations.RunPython(add_owner, reverse_code=migrations.RunPython.noop),
    ]
