# Generated by Django 4.0.1 on 2022-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_comment_downvoted_users_comment_upvoted_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_comments',
            field=models.IntegerField(default=0, verbose_name='number of comments'),
        ),
    ]
