# Generated by Django 4.0.4 on 2022-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_add_owner_pfp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='owner_pfp_url',
            field=models.CharField(default='', max_length=256, verbose_name='owner pfp url'),
        ),
    ]
