# Generated by Django 4.0.1 on 2022-01-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_guest_email_alter_guest_is_banned_and_more'),
        ('BlogApp', '0009_alter_comment_author_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='saved_by',
            field=models.ManyToManyField(related_name='comment_saved_by', to='user.Guest', verbose_name='comment saved by'),
        ),
        migrations.AddField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(related_name='post_saved_by', to='user.Guest', verbose_name='post saved by'),
        ),
    ]
