# Generated by Django 4.0.1 on 2022-01-29 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='registration date')),
                ('email', models.EmailField(default='example@blog.com', max_length=254, verbose_name='email')),
                ('phone', models.IntegerField(blank=True, default=111111)),
                ('profile_picture', models.ImageField(blank=True, default='profile.png', null=True, upload_to='', verbose_name='profile picture')),
                ('skype', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(max_length=256, null=True, unique=True, verbose_name='token')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='moderation status')),
                ('is_banned', models.BooleanField(default=False, verbose_name='is banned')),
                ('is_muted', models.BooleanField(default=False, verbose_name='is muted')),
                ('last_ban_date', models.DateTimeField(blank=True, null=True, verbose_name='last ban date')),
                ('rating', models.IntegerField(default=0, verbose_name='rating')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
