# Generated by Django 3.2.5 on 2021-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_guest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='token',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
