# Generated by Django 4.0.1 on 2022-05-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_guest_name_alter_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.IntegerField(blank=True, default=111111, null=True),
        ),
    ]
