# Generated by Django 4.0.1 on 2022-05-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.IntegerField(blank=True, default=111111, null=True, verbose_name='phone'),
        ),
    ]
