# Generated by Django 3.2.9 on 2022-01-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_guest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_ban_date',
            field=models.DateTimeField(null=True),
        ),
    ]
