# Generated by Django 3.2.9 on 2022-01-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220106_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='last_ban_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
