# Generated by Django 3.2.9 on 2022-01-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_guest_last_ban_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
