# Generated by Django 3.2.9 on 2022-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_guest_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='moderation status'),
        ),
    ]
