# Generated by Django 4.0.6 on 2022-08-08 12:39

from django.db import migrations


def add_default_pfp(apps, schema_editor):
    guest_model = apps.get_model('user', 'Guest')
    for row in guest_model.objects.all():
        row.profile_picture = '/static/images/profile.png'
        row.save(update_fields=['profile_picture'])
    comment_model = apps.get_model('BlogApp', 'Comment')
    for row in comment_model.objects.filter(owner_pfp_url=None):
        row.owner_pfp_url = '/static/images/profile.png'
        row.save(update_fields=['owner_pfp_url'])



class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_guest_profile_picture'),
    ]

    operations = [
        migrations.RunPython(add_default_pfp, reverse_code=migrations.RunPython.noop)
    ]
