# Generated by Django 4.0.1 on 2022-01-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220107_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(default='example@blog.com', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='is banned'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_muted',
            field=models.BooleanField(default=False, verbose_name='is muted'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_ban_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last ban date'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='token',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='token'),
        ),
    ]
